# Generated by Django 5.2.5 on 2025-08-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('planning_officer', 'Planning Officer'), ('statistics_officer', 'Statistics Officer'), ('head_of_division', 'Head of Division'), ('head_of_department', 'Head of Department')], default='planning_officer', max_length=32),
        ),
    ]
