# Generated by Django 5.2.5 on 2025-09-09 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_plan_status_statistic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('planning_officer', 'Planning Officer'), ('statistics_officer', 'Statistics Officer'), ('head_of_division', 'Head of Division'), ('head_of_department', 'Head of Department'), ('director_general', 'Director General')], default='planning_officer', max_length=32),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('used_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('projection', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=32)),
                ('old_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='login.budget')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget History',
                'verbose_name_plural': 'Budget History',
                'ordering': ['-changed_at'],
            },
        ),
    ]
